# Generated by Django 3.0.11 on 2021-01-23 16:46

import django.db.models.deletion
import solid_backend.content.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ais_content", "0002_create_formal_aspect_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ware",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacture",
                    models.CharField(
                        choices=[
                            ("Freigeformt / Handgemacht", "Freigeformt / Handgemacht"),
                            ("Langsame Töpferscheibe", "Langsame Töpferscheibe"),
                            (
                                "Scheibengedreht (Schnelle Töpferscheibe)",
                                "Scheibengedreht (Schnelle Töpferscheibe)",
                            ),
                            ("Modelgeformt", "Modelgeformt"),
                            ("Kombinierte Technik", "Kombinierte Technik"),
                            ("Sonstiges", "Sonstiges"),
                        ],
                        max_length=40,
                        verbose_name="Herstellungsart",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("Weich", "Weich"),
                            ("Mittel", "Mittel"),
                            ("Hart", "Hart"),
                            ("Klingend hart", "Klingend hart"),
                        ],
                        max_length=13,
                        verbose_name="Brand",
                    ),
                ),
                (
                    "brand_atm",
                    models.CharField(
                        choices=[
                            ("Reduzierender Brand", "Reduzierender Brand"),
                            ("Oxidierender Brand", "Oxidierender Brand"),
                            ("Kombinierte Verfahren", "Kombinierte Verfahren"),
                        ],
                        max_length=21,
                        verbose_name="Brennatmosphäre",
                    ),
                ),
                ("color", models.CharField(max_length=200, verbose_name="Farbe")),
                (
                    "ornament",
                    solid_backend.content.fields.ConcatCharField(
                        blank=True,
                        concat_choices=[
                            (
                                ("kammstrichverziert", "kammstrichverziert"),
                                (
                                    "mit Applikation versehen (frei Hand)",
                                    "mit Applikation versehen (frei Hand)",
                                ),
                                (
                                    "mt Applikation versehen (aus der Model)",
                                    "mt Applikation versehen (aus der Model)",
                                ),
                                ("bemalt", "bemalt"),
                                ("glasiert", "glasiert"),
                                ("monochrom bemalt", "monochrom bemalt"),
                                ("polychrom bemalt", "polychrom bemalt"),
                                ("bichrom bemalt", "bichrom bemalt"),
                                ("Barbotine-Technik", "Barbotine-Technik"),
                                ("unverziert", "unverziert"),
                                ("modelgeformt ", "modelgeformt"),
                                ("Sonstiges", "Sonstiges"),
                                (
                                    "Komplexe Merkmalskombination",
                                    "Komplexe Merkmalskombination",
                                ),
                            ),
                            (
                                ("kammstrichverziert", "kammstrichverziert"),
                                (
                                    "mit Applikation versehen (frei Hand)",
                                    "mit Applikation versehen (frei Hand)",
                                ),
                                (
                                    "mt Applikation versehen (aus der Model)",
                                    "mt Applikation versehen (aus der Model)",
                                ),
                                ("bemalt", "bemalt"),
                                ("glasiert", "glasiert"),
                                ("monochrom bemalt", "monochrom bemalt"),
                                ("polychrom bemalt", "polychrom bemalt"),
                                ("bichrom bemalt", "bichrom bemalt"),
                                ("Barbotine-Technik", "Barbotine-Technik"),
                                ("unverziert", "unverziert"),
                                ("modelgeformt ", "modelgeformt"),
                                ("Sonstiges", "Sonstiges"),
                                (
                                    "Komplexe Merkmalskombination",
                                    "Komplexe Merkmalskombination",
                                ),
                            ),
                            (
                                ("kammstrichverziert", "kammstrichverziert"),
                                (
                                    "mit Applikation versehen (frei Hand)",
                                    "mit Applikation versehen (frei Hand)",
                                ),
                                (
                                    "mt Applikation versehen (aus der Model)",
                                    "mt Applikation versehen (aus der Model)",
                                ),
                                ("bemalt", "bemalt"),
                                ("glasiert", "glasiert"),
                                ("monochrom bemalt", "monochrom bemalt"),
                                ("polychrom bemalt", "polychrom bemalt"),
                                ("bichrom bemalt", "bichrom bemalt"),
                                ("Barbotine-Technik", "Barbotine-Technik"),
                                ("unverziert", "unverziert"),
                                ("modelgeformt ", "modelgeformt"),
                                ("Sonstiges", "Sonstiges"),
                                (
                                    "Komplexe Merkmalskombination",
                                    "Komplexe Merkmalskombination",
                                ),
                            ),
                        ],
                        default="",
                        max_length=200,
                        seperators=[", ", " und "],
                        verbose_name="Verzeirungsart",
                    ),
                ),
                (
                    "magerungsart",
                    models.CharField(
                        choices=[
                            ("Ungemagert", "Ungemagert"),
                            ("Vegetabil", "Vegetabil"),
                            (
                                "Vegetabil mit mineralischem Beischlag",
                                "Vegetabil mit mineralischem Beischlag",
                            ),
                            (
                                "Vegetabil mit Schamott und mineralischem Beischlag",
                                "Vegetabil mit Schamott und mineralischem Beischlag",
                            ),
                            ("Mineralisch", "Mineralisch"),
                            (
                                "Mineralisch mit vegetabilem Beischlag",
                                "Mineralisch mit vegetabilem Beischlag",
                            ),
                            (
                                "Mineralisch mit Schamott und vegetabilem Beischlag",
                                "Mineralisch mit Schamott und vegetabilem Beischlag",
                            ),
                            ("Schamott", "Schamott"),
                            (
                                "Schamott mit vegetabilem Beischlag",
                                "Schamott mit vegetabilem Beischlag",
                            ),
                            (
                                "Schamott mit mineralischem Beischlag",
                                "Schamott mit mineralischem Beischlag",
                            ),
                            (
                                "Schamott mit vegetabilem und mineralischem Beischlag",
                                "Schamott mit vegetabilem und mineralischem Beischlag",
                            ),
                            (
                                "Komplexe Merkmalskombination",
                                "Komplexe Merkmalskombination",
                            ),
                            ("Weiteres ", "Weiteres"),
                        ],
                        max_length=52,
                        verbose_name="Magerungsart",
                    ),
                ),
                (
                    "magerungsmenge",
                    models.CharField(
                        choices=[
                            ("0%", "0%"),
                            ("1-5%", "1-5%"),
                            ("6-10%", "6-10%"),
                            ("11-15%", "11-15%"),
                            ("16-20%", "16-20%"),
                            ("21-25%", "21-25%"),
                            ("26-30%", "26-30%"),
                            ("31-35%", "31-35%"),
                            ("36-40%", "36-40%"),
                            ("41-45%", "41-45%"),
                            ("46-50%", "46-50%"),
                            ("51-55%", "51-55%"),
                            ("56-60%", "56-60%"),
                            ("61-65%", "61-65%"),
                            ("66-70%", "66-70%"),
                            ("71-75%", "71-75%"),
                            ("76-80%", "76-80%"),
                            ("81-85%", "81-85%"),
                            ("86-90%", "86-90%"),
                            ("91-95%", "91-95%"),
                            ("96-100%", "96-100%"),
                        ],
                        max_length=7,
                        verbose_name="Magerungsmenge",
                    ),
                ),
                (
                    "magerung_size",
                    models.CharField(
                        choices=[
                            ("Sehr klein", "Sehr klein"),
                            ("Klein", "Klein"),
                            ("Mittel", "Mittel"),
                            ("Groß", "Groß"),
                            ("Sehr Groß", "Sehr Groß"),
                        ],
                        max_length=10,
                        verbose_name="Magerungsgröße",
                    ),
                ),
                (
                    "magerung_dist",
                    models.CharField(
                        choices=[
                            ("Zufällig verteilt", "Zufällig verteilt"),
                            ("Gleichmäßig verteilt", "Gleichmäßig verteilt"),
                        ],
                        max_length=20,
                        verbose_name="Magerungsverteilung",
                    ),
                ),
                (
                    "magerung_form",
                    models.CharField(
                        choices=[
                            ("Rundlich", "Rundlich"),
                            ("Länglich", "Länglich"),
                            ("Muschelig", "Muschelig"),
                            ("Winkelig", "Winkelig"),
                        ],
                        max_length=9,
                        verbose_name="Magerungsform",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        max_length=400, null=True, blank=True, verbose_name="Bemerkung"
                    ),
                ),
                (
                    "find",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ware",
                        to="ais_content.Find",
                        verbose_name="Fundstück",
                    ),
                ),
            ],
            options={"verbose_name": "Ware", "verbose_name_plural": "Waren",},
        ),
    ]
