# Generated by Django 3.0.11 on 2021-04-21 11:25

import solid_backend.content.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ais_content", "0006_remove_systematics"),
    ]

    operations = [
        migrations.AddField(
            model_name="find",
            name="origin",
            field=models.TextField(blank=True, max_length=500, verbose_name="Herkunft"),
        ),
        migrations.AlterField(
            model_name="ware",
            name="ornament",
            field=solid_backend.content.fields.ConcatCharField(
                blank=True,
                concat_choices=[
                    (
                        ("kammstrichverziert", "kammstrichverziert"),
                        (
                            "mit Applikation versehen (frei Hand)",
                            "mit Applikation versehen (frei Hand)",
                        ),
                        (
                            "mt Applikation versehen (aus der Model)",
                            "mt Applikation versehen (aus der Model)",
                        ),
                        ("bemalt", "bemalt"),
                        ("glasiert", "glasiert"),
                        ("monochrom bemalt", "monochrom bemalt"),
                        ("polychrom bemalt", "polychrom bemalt"),
                        ("bichrom bemalt", "bichrom bemalt"),
                        ("Barbotine-Technik", "Barbotine-Technik"),
                        ("unverziert", "unverziert"),
                        ("modelgeformt ", "modelgeformt"),
                        ("Sonstiges", "Sonstiges"),
                        (
                            "Komplexe Merkmalskombination",
                            "Komplexe Merkmalskombination",
                        ),
                    ),
                    (
                        ("kammstrichverziert", "kammstrichverziert"),
                        (
                            "mit Applikation versehen (frei Hand)",
                            "mit Applikation versehen (frei Hand)",
                        ),
                        (
                            "mt Applikation versehen (aus der Model)",
                            "mt Applikation versehen (aus der Model)",
                        ),
                        ("bemalt", "bemalt"),
                        ("glasiert", "glasiert"),
                        ("monochrom bemalt", "monochrom bemalt"),
                        ("polychrom bemalt", "polychrom bemalt"),
                        ("bichrom bemalt", "bichrom bemalt"),
                        ("Barbotine-Technik", "Barbotine-Technik"),
                        ("unverziert", "unverziert"),
                        ("modelgeformt ", "modelgeformt"),
                        ("Sonstiges", "Sonstiges"),
                        (
                            "Komplexe Merkmalskombination",
                            "Komplexe Merkmalskombination",
                        ),
                    ),
                    (
                        ("kammstrichverziert", "kammstrichverziert"),
                        (
                            "mit Applikation versehen (frei Hand)",
                            "mit Applikation versehen (frei Hand)",
                        ),
                        (
                            "mt Applikation versehen (aus der Model)",
                            "mt Applikation versehen (aus der Model)",
                        ),
                        ("bemalt", "bemalt"),
                        ("glasiert", "glasiert"),
                        ("monochrom bemalt", "monochrom bemalt"),
                        ("polychrom bemalt", "polychrom bemalt"),
                        ("bichrom bemalt", "bichrom bemalt"),
                        ("Barbotine-Technik", "Barbotine-Technik"),
                        ("unverziert", "unverziert"),
                        ("modelgeformt ", "modelgeformt"),
                        ("Sonstiges", "Sonstiges"),
                        (
                            "Komplexe Merkmalskombination",
                            "Komplexe Merkmalskombination",
                        ),
                    ),
                ],
                default="",
                max_length=200,
                seperators=[", ", " und "],
                verbose_name="Verzierungsart",
            ),
        ),
    ]
