# Generated by Django 3.0.11 on 2021-04-21 14:46

from django.db import migrations, models


def lowercase(apps, schema_editor):
    """
    Transform all values to start with lowercase letters.
    """

    Ware = apps.get_model("ais_content", "Ware")

    for obj in Ware.objects.all():

        if obj.magerung_size == "sehr Groß":
            obj.magerung_size = "sehr groß"

        obj.save()


def uppercase(apps, schema_editor):
    """
    Transform all values to start with capital letters.
    """

    trafo_func = lambda s: s.capitalize()
    Ware = apps.get_model("ais_content", "Ware")

    for obj in Ware.objects.all():

        if obj.magerung_size == "sehr groß":
            obj.magerung_size = "sehr Groß"

        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ais_content', '0009_auto_20210421_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='brand',
            field=models.CharField(blank=True, choices=[('weich', 'weich'), ('mittel', 'mittel'), ('hart', 'hart'), ('klingend hart', 'klingend hart')], max_length=13, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='brand_atm',
            field=models.CharField(blank=True, choices=[('reduzierender Brand', 'reduzierender Brand'), ('oxidierender Brand', 'oxidierender Brand'), ('kombinierte Verfahren', 'kombinierte Verfahren')], max_length=21, null=True, verbose_name='Brennatmosphäre'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='magerung_dist',
            field=models.CharField(blank=True, choices=[('zufällig verteilt', 'zufällig verteilt'), ('gleichmäßig verteilt', 'gleichmäßig verteilt')], max_length=20, null=True, verbose_name='Magerungsverteilung'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='magerung_form',
            field=models.CharField(blank=True, choices=[('rundlich', 'rundlich'), ('länglich', 'länglich'), ('muschelig', 'muschelig'), ('winkelig', 'winkelig')], max_length=9, null=True, verbose_name='Magerungsform'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='magerung_size',
            field=models.CharField(blank=True, choices=[('sehr klein', 'sehr klein'), ('klein', 'klein'), ('mittel', 'mittel'), ('groß', 'groß'), ('sehr groß', 'sehr groß')], max_length=10, null=True, verbose_name='Magerungsgröße'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='magerungsart',
            field=models.CharField(blank=True, choices=[('ungemagert', 'ungemagert'), ('vegetabil', 'vegetabil'), ('vegetabil mit mineralischem Beischlag', 'vegetabil mit mineralischem Beischlag'), ('vegetabil mit Schamott und mineralischem Beischlag', 'vegetabil mit Schamott und mineralischem Beischlag'), ('mineralisch', 'mineralisch'), ('mineralisch mit vegetabilem Beischlag', 'mineralisch mit vegetabilem Beischlag'), ('mineralisch mit Schamott und vegetabilem Beischlag', 'mineralisch mit Schamott und vegetabilem Beischlag'), ('Schamott', 'Schamott'), ('Schamott mit vegetabilem Beischlag', 'Schamott mit vegetabilem Beischlag'), ('Schamott mit mineralischem Beischlag', 'Schamott mit mineralischem Beischlag'), ('Schamott mit vegetabilem und mineralischem Beischlag', 'Schamott mit vegetabilem und mineralischem Beischlag'), ('komplexe Merkmalskombination', 'komplexe Merkmalskombination'), ('Weiteres ', 'Weiteres')], max_length=52, null=True, verbose_name='Magerungsart'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='magerungsmenge',
            field=models.CharField(blank=True, choices=[('0%', '0%'), ('1-5%', '1-5%'), ('6-10%', '6-10%'), ('11-15%', '11-15%'), ('16-20%', '16-20%'), ('21-25%', '21-25%'), ('26-30%', '26-30%'), ('31-35%', '31-35%'), ('36-40%', '36-40%'), ('41-45%', '41-45%'), ('46-50%', '46-50%'), ('51-55%', '51-55%'), ('56-60%', '56-60%'), ('61-65%', '61-65%'), ('66-70%', '66-70%'), ('71-75%', '71-75%'), ('76-80%', '76-80%'), ('81-85%', '81-85%'), ('86-90%', '86-90%'), ('91-95%', '91-95%'), ('96-100%', '96-100%')], max_length=7, null=True, verbose_name='Magerungsmenge'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='manufacture',
            field=models.CharField(blank=True, choices=[('freigeformt / Handgemacht', 'freigeformt / Handgemacht'), ('langsame Töpferscheibe', 'langsame Töpferscheibe'), ('scheibengedreht (Schnelle Töpferscheibe)', 'scheibengedreht (Schnelle Töpferscheibe)'), ('modelgeformt', 'modelgeformt'), ('kombinierte Technik', 'kombinierte Technik'), ('sonstiges', 'sonstiges')], max_length=40, null=True, verbose_name='Herstellungsart'),
        ),
        migrations.RunPython(code=lowercase, reverse_code=uppercase),
    ]
