# Generated by Django 3.0.11 on 2021-06-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ais_content', '0011_auto_20210422_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='find',
            options={'ordering': ('name',), 'verbose_name': 'Fundstück', 'verbose_name_plural': 'Fundstücke'},
        ),
    ]
