# Generated by Django 3.0.11 on 2022-01-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ais_content", "0013_auto_20210920_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="find",
            name="source",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Publikation"
            ),
        ),
    ]
