# Generated by Django 3.2.20 on 2023-07-07 13:48

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


def move_fields_from_find_to_general_info(apps, schema_editor):
    Find = apps.get_model("ais_content", "Find")
    GeneralInformation = apps.get_model("ais_content", "GeneralInformation")

    for obj in Find.objects.all():
        GeneralInformation.objects.create(
            name=obj.name,
            origin=obj.origin,
            storage=obj.storage,
            find_number=obj.find_number,
            inven_number=obj.inven_number,
            source=obj.source,
            description=obj.description,
            find=obj
        )


def move_fields_from_general_info_to_find(apps, schema_editor):
    Find = apps.get_model("ais_content", "Find")
    for obj in Find.objects.all():
        general_info = obj.general_info
        obj.name = general_info.name
        obj.origin = general_info.origin
        obj.storage = general_info.storage
        obj.find_number = general_info.find_number
        obj.inven_number = general_info.inven_number
        obj.source = general_info.source
        obj.description = general_info.description
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0005_alter_treenode_name_attributes'),
        ('ais_content', '0014_auto_20220128_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('origin', models.TextField(blank=True, max_length=500, verbose_name='Herkunft')),
                ('storage',
                 models.CharField(blank=True, max_length=300, null=True, verbose_name='Stadt, Museum/Sammlung')),
                ('find_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fundnummer')),
                ('inven_number',
                 models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Inventarnummer')),
                ('source', models.CharField(blank=True, max_length=300, null=True, verbose_name='Publikation')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Beschreibung')),
                ('find',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_information',
                                      to='ais_content.find', verbose_name='Allgemein')),
            ],
        ),
        migrations.RunPython(move_fields_from_find_to_general_info, move_fields_from_general_info_to_find),
        migrations.AlterModelOptions(
            name='find',
            options={'verbose_name': 'Fundstück', 'verbose_name_plural': 'Fundstücke'},
        ),
        migrations.RemoveField(
            model_name='find',
            name='description',
        ),
        migrations.RemoveField(
            model_name='find',
            name='find_number',
        ),
        migrations.RemoveField(
            model_name='find',
            name='inven_number',
        ),
        migrations.RemoveField(
            model_name='find',
            name='name',
        ),
        migrations.RemoveField(
            model_name='find',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='find',
            name='source',
        ),
        migrations.RemoveField(
            model_name='find',
            name='storage',
        ),
        migrations.AlterField(
            model_name='find',
            name='tree_node',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                             related_name='find_related', related_query_name='finds',
                                             to='content.treenode'),
        ),
    ]
